import gibson from '../assets/gibson.jpg'
import ibanez from '../assets/ibanez.png'
import lag from '../assets/lag.jpg'
import musicman from '../assets/musicman.jpg'
import yamaha from '../assets/yamaha.jpg'

export const guitarList = [
    {
        id: 1,
        Style: 'Rock',
        Marque: 'Gibson',
        Type: 'Electrique',
        Gamme: 'Pro',
        isBestSale: true,
        cover: gibson,
    },
    {
        id: 2,
        Style: 'Rock',
        Marque: 'Lag',
        Type: 'Sèche',
        Gamme: 'Pro',
        isBestSale: true,
        cover: lag,
    },
    {
        id: 3,
        Style: 'Blues',
        Marque: 'Ibanez',
        Type: 'Acoustique',
        Gamme: 'Pro',
        isBestSale: false,
        cover: ibanez,
    },
    {
        id: 4,
        Style: 'Blues',
        Marque: 'Musicman',
        Type: 'Electrique/Acoustique',
        Gamme: 'Pro',
        isBestSale: true,
        cover: musicman,
    },
    {
        id: 5,
        Style: 'Jazz',
        Marque: 'Yamaha',
        Type: 'Electrique/Sèche',
        Gamme: 'Débutant',
        isBestSale: false,
        cover: yamaha,
    },
    {
        id: 6,
        Style: 'Jazz',
        Marque: 'Gibson',
        Type: 'Sèche/Acoustique',
        Gamme: 'Débutant',
        isBestSale: true,
        cover: gibson,
    },
    {
        id: 7,
        Style: 'Métal',
        Marque: 'Lag',
        Type: 'Electrique/Enfant',
        Gamme: 'Amateur',
        isBestSale: false,
        cover: lag,
    },
    {
        id: 8,
        Style: 'Métal',
        Marque: 'Ibanez',
        Type: 'Electrique/Adulte',
        Gamme: 'Amateur',
        isBestSale: true,
        cover: ibanez,
    },
    {
        id: 9,
        Style: 'Funck',
        Marque: 'Musicman',
        Type: 'Sèche/Enfant',
        Gamme: 'Débutant',
        isBestSale: true,
        cover: musicman,
    },
    {
        id: 10,
        Style: 'Funck',
        Marque: 'Yamaha',
        Type: 'Acoustique/Enfant',
        Gamme: 'Amateur',
        isBestSale: false,
        cover: yamaha,
    },
]
